### ISSUE TITLE
Feature request: persistent rulers.

### ISSUE THREAD

**Issue by Lee-Adamson** [SeamusFinlayson/owlbear-measure#7]
I like your ruler because it is a nice thin dotted line rather than the big fat thing that is the built-in ruler.

But I wish your extension could create persistent rulers the way the built-in ruler does when you double click.  I use this feature for velocity and acceleration vectors in Classic Traveller space combat.  My procedure is to create a persistent ruler, move it to the prop layer using the Outliner extension (so that it goes beneath the ship tokens), and then attach it and the ship token together such that the tail of the ruler is attached to the token and I can drag the head of the ruler around where-ever when it is selected.  Then I use a second temporary persistent ruler on a more uppermost layer to apply the acceleration vectors each turn.

Added bonuses would be the ability to turn off grid snapping on all grid types and put an arrow on one end.

Thanks for your consideration!  :D

![image](https://github.com/user-attachments/assets/b5f81df2-4873-46ef-b575-ab79b960d3cf)

**Comment by SeamusFinlayson** [comment]
So right now it does support persistent rulers, you have to press enter at the end of a measurement, but you're limited to one per user so I see how that doesn't really fit your use case. I can look at expanding that limit.

Upon further investigation though, it doesn't look like I'm able to really support moving rulers around like this because the rulers this extension uses are made out of like 4 different components and dragging them around together is already not super well supported by Owlbear Rodeo. 

A dedicated extension could probably support this use case specifically though, generating the rulers based on the token itself, but that is not this extension.
